repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        additional_dependencies:
        - apache-airflow==2.8.0
        - apache-airflow-providers-postgres==5.6.0
        - apache-airflow-providers-common-sql==1.7.2
        - dune-client==1.3.0
        - pandas==2.0.3
        - numpy==1.24.3
        - pytest==7.4.0
        - gspread==6.1.2
        args:
        - --disable=all
        - --enable=E0401
        - --errors-only
-   repo: local
    hooks:
    -   id: requirements
        name: requirements
        entry: pip install -r requirements.txt
        language: system
        pass_filenames: false
        always_run: true
#    -   id: pytest  # Commenting out the pytest hook
#        name: pytest
#        entry: pytest
#        language: system
#        types: [python]
#        pass_filenames: false
#        always_run: true
    # -   id: airflow-dags-validate
    #     name: Validate Airflow DAGs
    #     entry: docker exec yuza-sosa-airflow-webserver-1 python /opt/airflow/dags/validate_dags.py
    #     language: system
    #     files: 'dags/.*\.py$'
